apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset="UTF-8">
        <title>a pretty new site</title>
        <meta name="description" content="here will be something soon.">
        </head>
        <body>
        <header>
          <br>
          <h3>Workshop sample website</h3>
          <br>
        <header>
        </body>
        </html>
