apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
        <html>
        <head>
        <meta charset="UTF-8">
        <title>a pretty new site</title>
        <meta name="description" content="here will be something soon.">
        </head>
        <body>
        <div>
          <br>
          Workshop sample website
          <br>
        </div>
        </body>
        </html>
