apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: jan379/apache:latest
        name: frontendcontainer
        volumeMounts:
        - mountPath: /usr/share/nginx/html # place index.php
          readOnly: true
          name: index-php
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - name: index-php
        configMap:
          name: index-php 
          items:
            - key: index.php 
              path: index.php
              
