apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html # place index.html
          readOnly: true
          name: index-html
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - name: index-html
        configMap:
          name: index-html 
          items:
            - key: index.html 
              path: index.html
              
