apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: jan379/php:latest
        name: backendcontainer
        volumeMounts:
        - mountPath: /usr/share/nginx/html # place index.php
          readOnly: true
          name: index-php
        ports:
        - containerPort: 9000
        resources: {}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: dbname
      volumes:
      - name: index-php
        configMap:
          name: index-php 
          items:
            - key: index.php 
              path: index.php
              
