apiVersion: v1
kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: cinder-dynamic-provisioner
      pv.kubernetes.io/provisioned-by: kubernetes.io/cinder
    labels:
      failure-domain.beta.kubernetes.io/zone: ix2
    name: test_volume 
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    cinder:
      volumeID: 320753ea-b82a-4f3e-8b36-3695c0a675f9
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - ix2
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
