apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: internal-loadbalancer-v1
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true" 
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
