apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets 
type: Opaque
stringData:
  admin-password: changeMeOrReplaceMe
  dbname: wordpress
  username: wordpressdbuser
  password: changeMeOrReplaceMe
